### ISSUE TITLE
WASM support for RNG

### ISSUE THREAD

**Issue by ccie18473** [ggez/good-web-game#60]
We see that all examples use something like:

qrand::srand(12345);

I tried to use the std SystemTime but got a panic:

PanicInfo { payload: Any { .. }, message: None, location: Location { file: "library/std/src/sys/wasm/../unsupported/time.rs", line: 39, col: 9 } }

What options do we have ?

**Comment by ozkriff** [comment]
`quad_rand::srand(miniquad::date::now() as _);`

**Comment by ccie18473** [comment]
solution works
