### ISSUE TITLE
incompatible gl.js version 

### ISSUE THREAD

**Issue by ccie18473** [ggez/good-web-game#61]
Been able to build and test successfully WASM targets under Ubuntu, Copied the files to a windows 10 machine and it worked fine. Copied the files to another windows 10 machine and it failed:
(Chrome logs)
js_bundle.js:1 WASM failed to load, probably incompatible gl.js version 
(anonymous) @ js_bundle.js:1
js_bundle.js:1 TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ js_bundle.js:1
How do I troubleshoot this ? I'm using js_bundle.js (0.1.26) and Python 3.7 basic web server.

**Comment by PSteinhaus** [comment]
I'm sadly no expert on this, but based on your errors it seems that your web server might be at fault here, see: https://github.com/not-fl3/macroquad/issues/291

**Comment by ccie18473** [comment]
It was indeed a problem with the python http server. Python was installed under "Program Files (x86)" and there was some kind of permissions issue. Python installed on another place and everything works fine. Thanks for the hints.
