### ISSUE TITLE
WASM failed to load, probably incompatible gl.js version

### ISSUE THREAD

**Issue by Szybet** [ggez/good-web-game#62]
When trying to launch my game using wasm, i get 2 errors at f12 in the browser:
```
WASM failed to load, probably incompatible gl.js version
(anonymous) @ js_bundle.js:1
```
```
TypeError: WebAssembly.instantiate(): Import #6 module="__wbindgen_placeholder__" error: module is not an object or function
    at js_bundle.js:1
(anonymous) @ js_bundle.js:1
```
Whot logs / code should i provide to help resolve the issue?
Also, for me, the same error appers when trying to launch the example, using instructions from the readme file.

**Comment by PSteinhaus** [comment]
That error implies that you're using some kind of dependency that requires wasm-bindgen, [which requires you to jump through some additional loops](https://github.com/not-fl3/macroquad/issues/212#issuecomment-835276147).

That's weird, as good-web-game on it's own shouldn't require any of this...
Even worse: I just tried to reproduce this and I couldn't even build for wasm (without adding a line like this that is:)
```rust
getrandom = { version = "0.2", features = ["js"] }
```
With that I can get it to build, but then we need wasm-bindgen to get that dependency to work, so I then run into the same error as you.

Were you able to build good-web-game without this line? If so I'd be interested in your lock-file.

**Comment by PSteinhaus** [comment]
Ok, I just pushed a commit that should fix this, for now.
I forced the use of `twox_hash 1.5.0`, so that `rand < 0.8` is used which avoids `getrandom`, so that the project compiles on wasm without the need for wasm-bindgen.

But this is really just a temporary fix. Once another dependency changes its dependencies to include getrandom we have to play this game again...

**Comment by Szybet** [comment]
> That error implies that you're using some kind of dependency that requires wasm-bindgen, [which requires you to jump through some additional loops](https://github.com/not-fl3/macroquad/issues/212#issuecomment-835276147).
> 
> That's weird, as good-web-game on it's own shouldn't require any of this... Even worse: I just tried to reproduce this and I couldn't even build for wasm (without adding a line like this that is:)
> 
> ```rust
> getrandom = { version = "0.2", features = ["js"] }
> ```
> 
> With that I can get it to build, but then we need wasm-bindgen to get that dependency to work, so I then run into the same error as you.
> 
> Were you able to build good-web-game without this line? If so I'd be interested in your lock-file.

I added ``` getrandom = { version = "0.2", features = ["js"] }``` earlier, it was required
wasm-bindgen did the job, thanks!
