### ISSUE TITLE
unresolved imports `quad_snd::decoder`, `quad_snd::mixer::Sound`, `quad_snd::mixer::SoundMixer`

### ISSUE THREAD

**Issue by denisgrib** [ggez/good-web-game#65]
![image](https://user-images.githubusercontent.com/1868912/173667251-ed73f183-0fe8-4ce9-867b-f28f81612e52.png)

**Comment by PSteinhaus** [comment]
I assume this is in gwg `0.3`?
I'd really advice you not to use this version anymore. `0.4.2` has a couple of really nice to have bug fixes (such as a fixed memory leak or these kinds of problems with wrong imports as well).

But on the other hand, I could release a quick `0.3.1` update trying to port most of the fixes and fixing your particular problem by changing

`quad-snd = "0.1.0-alpha.1"`` to
`quad-snd = "=0.1.0-alpha.1"` 

in Cargo.toml.
