### ISSUE TITLE
WASM runtime errors

### ISSUE THREAD

**Issue by MOj0** [ggez/good-web-game#68]
I built the astroblasto example, like it is specified in the [README](https://github.com/ggez/good-web-game#webassembly). The build works, but when I open it in browser, I immediately get the following errors:

- gl version mismatch: `Version mismatch: gl.js version is: 0.1.26, rust sapp-wasm crate version is: 0.3.13`
- some sort of audio error: `Uncaught TypeError: AudioParam.value setter: Value being assigned is not a finite floating-point value.
audio_play_buffer https://psteinhaus.github.io/js/js_bundle.js:1    
animation https://psteinhaus.github.io/js/js_bundle.js:1`
- input handling error(s): `Uncaught RuntimeError: unreachable executed
    onkeydown https://psteinhaus.github.io/js/js_bundle.js:1`

Also I remember this worked a couple of months ago, so there has to be a breaking change somewhere else, that needs to be resolved.

**Comment by PSteinhaus** [comment]
Ah yes, this is a recurring problem I keep seeming to forget. Sorry about that.

We need to make sure that the gl.js version is compatible to the currently used miniquad and quad-snd versions. Usually this can be done in a rather easy way by just mirroring [this file](https://raw.githubusercontent.com/not-fl3/macroquad/master/js/mq_js_bundle.js) from the macroquad repo. But this time I think I forgot to do that, as things worked well enough still on my machine it seems.

I updated the file at https://psteinhaus.github.io/js/js_bundle.js to match the current version of the macroquad file now.

Macroquad currently uses the same version of miniquad as we do, if I'm not mistaken, and quad-snd 0.2 as we do, so this should work, I hope.

Could you please check and see if this solves the problem?
